### ISSUE TITLE
MX is not found

### ISSUE THREAD

**Issue by raghavmishra** [Octoberfest7/DNS_Tunneling#1]
Sorry, I couldn't find a way to contact you. I have configured the coredns but when I send a MX query to DNS Server I get this,
./coredns
.:53
dns.abc.com.:53
CoreDNS-1.10.1
linux/amd64, go1.19.3, 915b74f2
[INFO] x.x.x.x:26517 - 38954 "A IN type=mx. udp 25 false 512" NXDOMAIN qr,aa,rd 144 0.000281684s

Can you please help on this?

**Comment by raghavmishra** [comment]
nslookup type=MX 1.dns.arista-onelogein.com                                                                                                                                                                 ─╯
Server:         1.dns.arista-onelogein.com
Address:        x.x.x.x#53

** server can't find type=MX: NXDOMAIN

**Comment by Octoberfest7** [comment]
Did you see that you need a '-' in front of type=? 
![image](https://user-images.githubusercontent.com/91164728/220732851-8b9c4a36-8ef9-4058-875d-26b76bbd3f42.png)

**Comment by raghavmishra** [comment]
Yes, I corrected that no luck. My Corefile for coredns looks like this,
```
.:53 {
	file dns.abc.com
	log
	errors
}
dns.abc.com:53 {
	file dns.abc.com
	log
	errors
}
```
My DNS records looks like this,
![Screenshot 2023-02-23 at 1 32 19 PM](https://user-images.githubusercontent.com/3175190/220852101-158651f4-4502-41c4-ab15-a25c392b8d36.png)

**Comment by raghavmishra** [comment]
I got it working with other domain. Thank you.
